### ISSUE TITLE
Add-KindleBook : You cannot call a method on a null-valued expression.

### ISSUE THREAD

**Issue by paschott** [mdjx/PSKindleWatch#1]
I like the idea of this, but trying to use the module, I get the above error on PS 5 and PS 7.  
Tried this with a book for one of my kids.

Add-KindleBook -BookURL "https://www.amazon.com/dp/B07TD6DZTC/"

Error:
Add-KindleBook : You cannot call a method on a null-valued expression.
At line:1 char:1
+ Add-KindleBook -BookURL "https://www.amazon.com/dp/B07TD6DZTC/"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Add-KindleBook], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Add-KindleBook

**Comment by mdjx** [comment]
Hey, thanks for bringing this to my attention. I've implemented a fix, can you please grab the updated version and test when you have a chance? Let me know how it goes, cheers!

**Comment by mdjx** [comment]
Hey @paschott, I believe this has been resolved so I'll close the issue, but please let me know if you continue to have problems.
